# Site settings
title: Cameron Sun
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Cameron Sun, a software engineer who lives in Seattle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.csun.io" # the base hostname & protocol for your site

author: Cameron Sun

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed

paginate: 8
paginate_path: "/:num/"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
