# Site settings
title: Cameron Sun
email: me@csun.io
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Cameron Sun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.csun.io" # the base hostname & protocol for your site
github_username:  csun

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
