# Site settings
title: Cameron Sun
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Cameron Sun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.csun.io" # the base hostname & protocol for your site

author:
  twitter: cam_sun

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 4
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
